DROP TABLE IF EXISTS `care_tz_billing_archieve_special`;
DROP TABLE IF EXISTS `care_tz_billing_special`;
DROP TABLE IF EXISTS `care_tz_druglist`;
DROP TABLE IF EXISTS `care_tz_drugs_reordering_level`;
DROP TABLE IF EXISTS `care_tz_drugsandservices_categories`;
DROP TABLE IF EXISTS `care_tz_drugsandservices_sub_categories`;
DROP TABLE IF EXISTS `care_tz_drugsandservices_update`;
DROP TABLE IF EXISTS `care_tz_eye_history1`;
DROP TABLE IF EXISTS `care_tz_eye_history2`;
DROP TABLE IF EXISTS `care_tz_eye_history3`;
DROP TABLE IF EXISTS `care_tz_eye_history4`;
DROP TABLE IF EXISTS `care_tz_eye_history5`;
DROP TABLE IF EXISTS `care_tz_grn_detail`;
DROP TABLE IF EXISTS `care_tz_grn_master`;
DROP TABLE IF EXISTS `care_tz_item_transfer`;
DROP TABLE IF EXISTS `care_tz_item_transfer_detail`;
DROP TABLE IF EXISTS `care_tz_location`;
DROP TABLE IF EXISTS `care_tz_pricedescription`;
DROP TABLE IF EXISTS `care_tz_purchase_order`;
DROP TABLE IF EXISTS `care_tz_purchase_order_detail`;
DROP TABLE IF EXISTS `care_tz_stock_in_hand`;
DROP TABLE IF EXISTS `care_tz_stock_supplier_lists`;
DROP TABLE IF EXISTS `care_tz_stock_suppliers`;
DROP TABLE IF EXISTS `care_tz_stock_transfer`;
DROP TABLE IF EXISTS `care_tz_store_info`;
DROP TABLE IF EXISTS `care_tz_village`;
DROP TABLE IF EXISTS `care_users_old`;
DROP TABLE IF EXISTS `custom_care_person_add_field`;
DROP TABLE IF EXISTS `custom_field_select_options`;
DROP TABLE IF EXISTS `custom_person_add_field_value`;
DROP TABLE IF EXISTS `mems_drug_list`;
DROP TABLE IF EXISTS `mems_special_other`;
DROP TABLE IF EXISTS `mems_supplies`;
DROP TABLE IF EXISTS `mems_supplies_labor`;
DROP TABLE IF EXISTS `tbl_who_icd10`;
DROP TABLE IF EXISTS `temp_list`;
DROP TABLE IF EXISTS `userrole_permission`;
ALTER TABLE `care_department` ADD COLUMN `max_appointments` int(10) NOT NULL DEFAULT 20 AFTER `consult_hours`;
ALTER TABLE `care_encounter` ADD COLUMN `pharmacy` varchar(20) NOT NULL AFTER `current_dept_nr`;
ALTER TABLE `care_encounter_prescription` ADD COLUMN `partcode` varchar(255) NOT NULL AFTER `article_item_number`, ADD COLUMN `materialcost` varchar(255) NOT NULL DEFAULT 0 AFTER `partcode`, ADD COLUMN `in_weberp` int(3) NOT NULL AFTER `sub_store`;
ALTER TABLE `care_icd10_en` ADD COLUMN `show` tinyint(2) NOT NULL DEFAULT 0 AFTER `extra_subclass`;
ALTER TABLE `care_op_med_doc` ADD COLUMN `anasthetist` varchar(25) NOT NULL AFTER `op_end`, ADD COLUMN `anaesthesia_type` varchar(15) NOT NULL AFTER `assistant`, ADD COLUMN `postorder` text NOT NULL AFTER `anaesthesia_type`, ADD COLUMN `indication` text NOT NULL AFTER `postorder`, ADD COLUMN `procedure_or` text NOT NULL AFTER `indication`, DROP COLUMN `class_m`, DROP COLUMN `class_l`, MODIFY COLUMN `class_s` varchar(18) NOT NULL AFTER `special`, MODIFY COLUMN `assistant` varchar(255) NOT NULL AFTER `scrub_nurse`;
ALTER TABLE `care_tz_billing_archive_elem` ADD COLUMN `notes` varchar(255) NOT NULL AFTER `description`, ADD COLUMN `close_deposit` tinyint(2) NOT NULL DEFAULT 0 AFTER `is_deposit_item`, MODIFY COLUMN `price` varchar(255) NOT NULL AFTER `days`, MODIFY COLUMN `materialcost` varchar(255) NOT NULL DEFAULT 0 AFTER `price`, MODIFY COLUMN `bank_ref` varchar(255) NOT NULL AFTER `sub_store`, MODIFY COLUMN `description` varchar(255) NOT NULL AFTER `insurance_id`, MODIFY COLUMN `is_transmit2ERP` tinyint(4) NOT NULL DEFAULT 1 AFTER `signed_by_follower`, MODIFY COLUMN `is_deposit_item` tinyint(1) NOT NULL DEFAULT 0 AFTER `is_transmit2ERP`, MODIFY COLUMN `current_dept_nr` smallint(3) NOT NULL AFTER `bank_ref`, MODIFY COLUMN `current_ward_nr` smallint(3) NOT NULL AFTER `current_dept_nr`;
ALTER TABLE `care_tz_company` ADD COLUMN `enable_member_expiry` tinyint(2) NOT NULL AFTER `modify_id`;
UPDATE `care_person` set `insurance_ID` =0 WHERE `insurance_ID` IN(SELECT id FROM care_tz_company WHERE name='CASH-PATIENT')

ALTER TABLE `care_encounter` ADD `nhif_auth_no` VARCHAR(15) NULL DEFAULT NULL AFTER `insurance_2_firm_id`;

INSERT INTO `care_menu_main` (`nr`, `sort_nr`, `name`, `LD_var`, `url`, `is_visible`, `hide_by`, `status`, `modify_id`, `modify_time`) VALUES ('28', '61', 'NHIF Claims', 'LDNHIFClaims', 'modules/nhif/nhif_pass.php', '1', '', '', '2011-08-24 15:44:37', '0000-00-00 00:00:00');